DATASET:
  TRAIN_ENCODED_DIR: /data/rohitrango/Implicit3DCNNTasks/brats2021_unimodal_99thpercentile/
  TRAIN_SEG_DIR: /data/rohitrango/BRATS2021/training/
ENCODE:
  DESIRED_RESOLUTION: 196
  LEVEL_DIM: 2
  MLABEL: 0
  MULTIMODAL: false
  NUM_EPOCHS_STAGE1: 20
  NUM_EPOCHS_STAGE2: 500
  NUM_POINTS: 100000
  SCORE_FN: uniform
  STAGE1_TRAIN_IMAGES: 250
NETWORK:
  ACTIVATION: LeakyReLU
  ACTIVATION_PARAM: 0.05
  BLOCK_CHANNELS:
  - 16
  - 16
  - 16
  - 16
  BLOCK_NUM_LAYERS:
  - 2
  - 2
  - 2
  - 2
  INPUT_CHANNELS: 8
  NAME: AbstractResNet
  OUTPUT_CHANNELS: 4
SEG:
  WEIGHT_CE: 0.0
  WEIGHT_DICE: 1.0
TRAIN:
  BASE_LR: 0.0002
  BATCH_SIZE: 4
  BRATS_SEGM_MODE: brats
  EPOCHS: 100
  LOGIT_TRANSFORM: sigmoid
  LR_SCHEDULER: poly
  NUM_WORKERS: 1
  OPTIMIZER: adam
  WEIGHT_DECAY: 0.0
VAL:
  EVAL_EVERY: 2
  STOP_AT: 10000
