## version 1.4 has same architecture as v1.3, but 
##   * layernorm is ON by default,
##   * shuffle_seed is True
##   * [NO] scale-range is 0.1 from 0.2  
##   * [NO] 4-fold cross validation  (val-4 always causes some problems)
##   * focal_loss is set to 0.25 (by default instead of ablating in v1.3)
DATASET:
  TRAIN_ENCODED_DIR: /data/rohitrango/Implicit3DCNNTasks/brats2021_unimodal
  TRAIN_SEG_DIR: /data/rohitrango/BRATS2021/training/
  SCALE_RANGE: 0.2
SEG:
  WEIGHT_FOCAL: 0.25
NETWORK:
  ACTIVATION: LeakyReLU
  USE_LAYERNORM: True
  ACTIVATION_PARAM: 0.05
  BLOCK_CHANNELS:
  - 16
  - 32
  - 32
  - 32
  - 32
  - 32
  BLOCK_NUM_LAYERS:
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  INPUT_CHANNELS: 8
  NAME: AbstractResNet
  OUTPUT_CHANNELS: 4
TRAIN:
  BASE_LR: 0.00025
  BATCH_SIZE: 1
  BRATS_SEGM_MODE: brats
  EPOCHS: 50
  LOGIT_TRANSFORM: sigmoid
  LR_SCHEDULER: poly
  NUM_WORKERS: 2
  OPTIMIZER: adam
  WEIGHT_DECAY: 1e-5
VAL:
  EVAL_EVERY: 1
  FOLD: 0
  MAX_FOLDS: 5
  STOP_AT: 10000
  RANDOM_SHUFFLE: True
