DATASET:
  TRAIN_ENCODED_DIR: /data/rohitrango/Implicit3DCNNTasks/brats2021_unimodal
  TRAIN_SEG_DIR: /data/rohitrango/BRATS2021/training/
NETWORK:
  ACTIVATION: LeakyReLU
  ACTIVATION_PARAM: 0.05
  BLOCK_CHANNELS:
  - 8
  - 16
  - 32
  - 64
  BLOCK_NUM_LAYERS:
  - 2
  - 2
  - 1
  - 1
  INPUT_CHANNELS: 8
  NAME: AbstractResNet
  OUTPUT_CHANNELS: 4
TRAIN:
  BASE_LR: 0.0002
  BATCH_SIZE: 2
  BRATS_SEGM_MODE: brats
  EPOCHS: 100
  LOGIT_TRANSFORM: sigmoid
  LR_SCHEDULER: poly
  NUM_WORKERS: 2
  OPTIMIZER: adam
  WEIGHT_DECAY: 1e-5
VAL:
  EVAL_EVERY: 2
  FOLD: 1
  STOP_AT: 10000
